<a href="https://colab.research.google.com/github/GUSTAVOIVANGQ/Genetic-algorithms/blob/main/knapsack_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# The knapsack problem using numpy
import numpy as np
v = [6,10,12]
w = [1,2,3]
W = 5
N = len(v)
# The zeros knapsack
m = np.zeros((N+1,W+1))
for row in range(N+1):
    for col in range(W+1):
      if row == 0 or col == 0:
        m[row][col] = 0
      elif w[row-1] > col:
        m[row][col] = m[row-1][col]
      else:
        m[row][col] = max(m[row-1][col], m[row-1][col-w[row-1]] + v[row-1])
print('La matriz es:')
print(m)
#Find what items are in the backpack m
i = N
j = W
print('Los elementos seleccionados para la mochila son:')
while (i>0 and j>0):
  if m[i][j] == m[i-1][j]:
    i = i-1
  else:
    print(i)
    j = j-w[i-1]
    i = i-1

La matriz es:
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  6.  6.  6.  6.  6.]
 [ 0.  6. 10. 16. 16. 16.]
 [ 0.  6. 10. 16. 18. 22.]]
Los elementos seleccionados para la mochila son:
3
2


In [ ]:
#The change-making problem
coins = [1,2,5]
amount = 7
d = len(coins)
m = np.zeros((d+1,amount+1))

#m[1,N]=N
#m[i,N]=m[i-1,N]  if di>N
#m[i,N] = min ( m[i-1,N] , m[i,N-di] + 1 )

for row in range(d+1):
    for col in range(amount+1):
      if(row == 1):
        m[row][col] = col
      elif coins[row-1] > col:
        m[row][col] = m[row-1][col]
      else:
        m[row][col] = min(m[row-1][col], m[row][col-coins[row-1]] + 1)
print('La matriz es:')
print(m)

# Finding coins are in the m.
i = d
j = amount
print('Los elementos seleccionados son:')
while (i>0 and j>0):
  if m[i][j] == m[i-1][j]:
    i = i-1
  else:
    print(coins[i-1])
    j = j-coins[i-1]
    i = i-1



La matriz es:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 1. 2. 2. 3. 3. 4.]
 [0. 1. 1. 2. 2. 1. 2. 2.]]
Los elementos seleccionados son:
5
2
